runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /
    static_files: dist/desafio-chek-front/index.html
    upload: dist/desafio-chek-front/index.html
  - url: /
    static_dir: dist/desafio-chek-front
